config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'

  mount Sidekiq::Web, at: '/sidekiq'

  namespace 'api' do
    resources :sensor_values, only: [:create] # due to reduce packet size
    resources :sensors, only: [] do
      resource :chart_setting, only: [:update]
      resources :sensor_values, only: [:index]
    end
  end

  resources :devices, only: [:index, :show, :create, :destroy] do
    resources :sensors, only: [:create, :update, :destroy]
  end

  root to: 'application#routing_error'
  match '*path', to: 'application#routing_error', via: :all

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chart_setting.rb
class ChartSetting < ApplicationRecord
  belongs_to :sensor
end

app/models/device.rb
class Device < ApplicationRecord
  has_many :sensors, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/sensor.rb
class Sensor < ApplicationRecord
  belongs_to :device
  has_many :sensor_values, dependent: :destroy
  has_one :chart_setting

  validates :name, presence: true
  validates :name, uniqueness: { scope: :device }
end

app/models/sensor_value.rb
class SensorValue < ApplicationRecord
  belongs_to :sensor

  validates :value, presence: true
end

app/controllers/api/application_controller.rb
module Api
  class ApplicationController < ActionController::API
    rescue_from Exception, with: :handle_500

    def handle_500
      head :internal_server_error
    end
  end
end

app/controllers/api/chart_settings_controller.rb
module Api
  class ChartSettingsController < Api::ApplicationController
    before_action :set_chart_setting

    def update
      if @setting.update(chart_params)
        head :ok
      else
        head :bad_request
      end
    end

    private

    def set_chart_setting
      @setting = ChartSetting.find_or_create_by(sensor_id: params[:sensor_id])
    end

    def chart_params
      params.require(:chart_setting).permit(
        :interval,
        :samples,
        :threshold,
        :date_format
      )
    end
  end
end

app/controllers/api/sensor_values_controller.rb
module Api
  class SensorValuesController < Api::ApplicationController
    def index
      values = ::SensorValuesFinder.new(params[:sensor_id], search_params).values
      render json: values
    end

    def create
      if SensorValue.insert_all(sensor_params)
        head :created
      else
        head :bad_request
      end
    end

    private

    def sensor_params
      ActionController::Parameters.new(JSON.parse(request.body.read))
      .permit(values: [
        :id,
        :val
      ])[:values].map{|item|
        item = {
          sensor_id: item[:id],
          value: item[:val],
          created_at: Time.zone.now,
          updated_at: Time.zone.now
        }
      }
    end

    def search_params
      params.permit(:count)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def routing_error
    redirect_to devices_path
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  def index
    @devices = Device.eager_load(:sensors).order(:id)
  end

  def show

  end

  def create
    @device = Device.new(device_params)
    if @device.save
      redirect_to action: :index
    else
      redirect_to action: :index
    end
  end

  def update
    @device.update(device_params)
    redirect_to @device
  end

  def destroy
    @device.destroy
    redirect_to action: :index
  end

  private

  def device_params
    params.require(:device).permit(:name)
  end

  def set_device
    @device = Device.eager_load(:sensors).find(params[:id])
  end

end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
  before_action :set_sensor, only: [:update, :destroy]

  def create
    Sensors::CreateService.new(sensor_params).execute
    redirect_to devices_path
  end

  def update
    @sensor.update(sensor_params)
    device_path(params[:device_id])
  end

  def destroy
    @sensor.destroy
    device_path(params[:device_id])
  end

  private

  def sensor_params
    params.require(:sensor).permit(:name)
        .merge(params.permit(:device_id))
  end

  def set_sensor
    @sensor = Sensor.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/devices/index.html.slim
.row
  .col-sm-1
  .col-sm-10
    table.table.table-hover.text-center
      thead.thead-light
        tr
          th Device ID
          th Name
          th Created
          th btn
      tbody
        - @devices.each do |device|
          tr onclick="flip_device_detail(#{device.id}, #{device.sensors.size+3});"
            td.align-middle.h6 id="device_id_row_#{device.id}" = device.id
            td.align-middle.h6 = link_to device.name, device_path(device)
            td.align-middle = device.created_at
            td.align-middle
              button.btn.btn-danger type="button" data-toggle="modal" data-target="#warning_delete_device#{device.id}_modal" Delete
              div.modal.fade id="warning_delete_device#{device.id}_modal" tabindex="-1" role="dialog" aria-hidden="true"
                div.modal-dialog role="document"
                  div.modal-content
                    div.modal-header
                      h4.modal-title.text-danger Warning
                      button.close type="button" data-dismiss="modal" aria-label="Close"
                        span aria-hidden="true" &times;
                    div.modal-body
                      h6 Selected device and sensors will be deleted!
                    div.modal-footer
                      button.btn.btn-secondary type="button" data-dismiss="modal" Close
                      = form_with url: device_path(device), method: :delete, local: true do |f|
                        = f.submit "Delete device", class: "btn btn-danger"

          - if device.sensors.size>0
            tr.bg-light style="display: none;" class="hidden_detail_#{device.id}"
              th Sensor ID
              th Name
              th
            - device.sensors.sort{|a,b| a.id<=>b.id}.each do |sensor|
              tr style="display: none;" class="hidden_detail_#{device.id}"
                td.align-middle = sensor.id
                td.align-middle = sensor.name
                td.align-middle
                  button.btn.btn-danger type="button" data-toggle="modal" data-target="#warning_delete_sensor#{sensor.id}_modal" Delete
                  div.modal.fade id="warning_delete_sensor#{sensor.id}_modal" tabindex="-1" role="dialog" aria-hidden="true"
                    div.modal-dialog role="document"
                      div.modal-content
                        div.modal-header
                          h4.modal-title.text-danger Warning
                          button.close type="button" data-dismiss="modal" aria-label="Close"
                            span aria-hidden="true" &times;
                        div.modal-body
                          h6 Selected Sensor will be deleted!
                        div.modal-footer
                          button.btn.btn-secondary type="button" data-dismiss="modal" Close
                          = form_with url: device_sensor_path(device, sensor), method: :delete, local: true do |f|
                            = f.submit "Delete sensor", class: "btn btn-danger"

          - else
            tr.bg-light style="display: none;" class="hidden_detail_#{device.id}"
              th colspan="3" No Sensors
          tr style="display: none;" class="hidden_detail_#{device.id}"
              = form_with model: Sensor.new, url: device_sensors_path(device), local: true do |f|
                th colspan="2"
                  = f.text_field :name, class: "form-control", required: true
                th
                  = f.submit "create new sensor", class: "btn btn-primary"

        = form_with model: Device.new, url: devices_path, local: true do |f|
          th colspan="3"
            = f.text_field :name, class: "form-control", required: true
          th
            = f.submit "create new device", class: "btn btn-primary"

javascript:
  function flip_device_detail(id, rows){
    $(`.hidden_detail_${id}`).each(function(index, element){
      $(element).toggle();
    });
    var table_data = $(`#device_id_row_${id}`)[0];
    table_data.rowSpan=(table_data.rowSpan==1 ? rows : 1);
  }

app/views/devices/show.html.slim
.row
  - @device.sensors.each do |sensor|
    .col-xl-6
      p.h1 = "#{sensor.id}. #{sensor.name}"
      .form-group
        = form_with model: sensor.chart_setting, url: api_sensor_chart_setting_path(sensor.id), method: :put do |f|
          .row
            .col-sm-4
              label.h6 for="interval_for_#{sensor.id}" Update Interval [ms]
              = f.number_field :interval, class: "form-control", min:"100", step: "100", id: "interval_for_#{sensor.id}", value: "#{sensor.chart_setting.interval}"
            .col-sm-4
              label.h6 for="samples_for_#{sensor.id}" Samples Count
              = f.number_field :samples, class: "form-control", min:"1", id: "samples_for_#{sensor.id}", value: "#{sensor.chart_setting.samples}"
            .col-sm-4
              label.h6 for="threshold_for_#{sensor.id}" Threshold
              = f.text_field :threshold, class: "form-control", id: "threshold_for_#{sensor.id}", value: "#{sensor.chart_setting.threshold}"
          .row
            .col-sm-6
              label.h6 for="date_format_for_#{sensor.id}" Date Format
              = f.text_field :date_format, class: "form-control", id: "date_format_for_#{sensor.id}", value: "#{sensor.chart_setting.date_format}"
            .col-sm-6
              .text-center
                p.h6 Save Chart Settings
                = f.submit "Save", class: "btn btn-primary"
      canvas id="canvas_for_#{sensor.id}"

      javascript:
        var chart_#{sensor.id} = new Chart($('#canvas_for_#{sensor.id}'), {
          type: 'line',
            data: {
              labels: [],
            datasets: [
                {
                  label: '#{sensor.name}',
                  data: [],
                  borderColor: "rgba(0,255,0,1)",
                  backgroundColor: "rgba(0,0,0,0)",
                  pointRadius: 1
                },
                {
                  label: 'th_#{sensor.name}',
                  data: [],
                  borderColor: "rgba(0,0,0,1)",
                  backgroundColor: "rgba(0,0,0,0)",
                  pointRadius: 0
                }
              ]
            },
            options: {
              animation: false,
              legend: {
                display: false
              },
              scales: {
                xAxes: [{
                  ticks: {
                    autoSkip: true,
                    maxTicksLimit: 5
                  }
                }]
              }
            }
          });

        function date_parser(date, format){
          format = format.replace(/YYYY/, date.getFullYear());
          format = format.replace(/MM/, date.getMonth()+1);
          format = format.replace(/DD/, date.getDate());

          format = format.replace(/hh/, date.getHours());
          format = format.replace(/mm/, date.getMinutes());
          format = format.replace(/ss/, date.getSeconds());
          return format;
        }

        function update_graph_#{sensor.id}(){
          $.get(
            "/api/sensors/#{sensor.id}/sensor_values",
            {count: $("#samples_for_#{sensor.id}").val()},
            function(data){
              const time_data = data.map(function(row){
                return date_parser(
                  new Date(row['created_at']),
                  $("#date_format_for_#{sensor.id}").val()
                );
              });
              const value_data = data.map(function(row){return row['value']});

              chart_#{sensor.id}.data.labels = time_data;

              chart_#{sensor.id}.data.datasets[0].data = value_data;

              const threshold = parseFloat($("#threshold_for_#{sensor.id}").val());

              if(Math.max.apply(null, value_data) >= threshold){
                chart_#{sensor.id}.data.datasets[0].borderColor = "rgba(255,0,0,1)";
              } else{
                chart_#{sensor.id}.data.datasets[0].borderColor = "rgba(0,255,0,1)";
              }

              if(!isNaN(threshold)){
                const len = value_data.length;
                chart_#{sensor.id}.data.datasets[1].data = new Array(len).fill(threshold);
              }
              else{
                chart_#{sensor.id}.data.datasets[1].data = [];
              }

              chart_#{sensor.id}.update();
          });

          if($("#interval_for_#{sensor.id}").length > 0){
            const interval = $("#interval_for_#{sensor.id}").val();
            setTimeout(update_graph_#{sensor.id}, Math.max(isNaN(interval)?1000:interval,500));
          }
        }

        update_graph_#{sensor.id}();

app/views/layouts/application.html.slim
html
  head
    title XDK110
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  body
    nav.navbar.navbar-dark.bg-dark
      span.navbar-brand.mb-0.h1 = link_to 'XDK110', devices_path, class: 'text-light'


    main.container-fluid
      = yield

    sass:
      body main
        padding-top: 1rem;